### ISSUE TITLE
Text color not inverted in reverse mode

### ISSUE THREAD

**Issue by aluttik** [daleroberts/itermplot#13]
Black text on dark background with `ITERMPLOT="rv"`:
<img width="559" alt="screen shot 2017-01-18 at 8 19 49 pm" src="https://cloud.githubusercontent.com/assets/10134357/22093594/c24f43ba-ddbb-11e6-90a3-6dd8b31d0b1a.png">

**Comment by daleroberts** [comment]
Strange, works for me. Is that script exactly the same as my example in the
`docs/` directory? Are you running version 0.17?

**Comment by aluttik** [comment]
I installed it for the first time a few minutes ago and copy-pasted your example directly into that file `git/itermplot_test.py` you see there


```
$ sudo -H pip install -U itermplot
Successfully installed itermplot-0.17 matplotlib-2.0.0 numpy-1.12.0 pyparsing-2.1.10 python-dateutil-2.6.0 pytz-2016.10 subprocess32-3.2.7
```
I'm running Python 2.7.13 on OSX 10.10.5 Yosemite with iTerm2 Build 3.0.13

**Comment by daleroberts** [comment]
Ok, I think I've fixed this Python 2 bug. Update to version 0.18: `pip
install -U itermplot`

**Comment by aluttik** [comment]
Wow, that was fast! It works great now.

<img width="550" alt="screen shot 2017-01-18 at 8 58 41 pm" src="https://cloud.githubusercontent.com/assets/10134357/22094248/f0573d94-ddc0-11e6-90a2-2054537386cd.png">

Thanks!

**Comment by daleroberts** [comment]
No problem, enjoy! :)
