### ISSUE TITLE
After clf() the reverse video option is forgotten

### ISSUE THREAD

**Issue by crosset** [daleroberts/itermplot#20]
All information is in the title.
Workaround: use close() instead of clf() to make a new figure, it works fine.

**Comment by daleroberts** [comment]
Fixed! clf() should now work and retain reverse video. Update with `pip install -U itermplot`

Could you test and confirm before I close this? Thanks.

**Comment by crosset** [comment]
I confirm (a bit late) it is working fine.
Thanks a lot for your work!
