### ISSUE TITLE
Missing .pdf extension in file when drag and drop image onto desktop

### ISSUE THREAD

**Issue by crosset** [daleroberts/itermplot#21]
Drag and drop is great, just that the extension is missing, so it doesn't display automatically. Just renaming the file and adding the .pdf extension works fine.

**Comment by daleroberts** [comment]
Fixed! Filename should be set now so you can drag and drop. Update with `pip install -U itermplot`

Could you test and confirm before I close this? Thanks.

**Comment by crosset** [comment]
Working perfectly too. Thanks.
