### ISSUE TITLE
Reverse video applied in pdf but background is white...

### ISSUE THREAD

**Issue by crosset** [daleroberts/itermplot#22]
The reverse video option is applied also in the pdf file which is produced in drag and drop, but it shouldn't as the background of the pdf file is white.

**Comment by daleroberts** [comment]
Unfortunately, I don't think this can be fixed as you are only dragging and dropping the image that iTerm2 displays. I'm not aware of any way for iTerm2 to send back a command that I could hook into so that the image is generated with a white background on a drag-drop event.
