### ISSUE TITLE
ipython support

### ISSUE THREAD

**Issue by peinan** [daleroberts/itermplot#24]
It's a very nice library that helps me to enhance my efficiency, but I think most people using matplotlib with python are working with ipython because it has the syntax highlight and the code complementation and many other benefits than normal python shell. So, I hope there will be an update to support ipython. Thanks.

**Comment by daleroberts** [comment]
Hi, it already supports iPython. See the screenshots on the Github page.

**Comment by peinan** [comment]
Thank you for a fast reply. Isn't it the case only run python code in the ipython shell? What I mean is to use matplotlib interactively like the python shell in your screenshot (Please see the screenshot below) . Please forgive me for my ignorance if I was doing the wrong way, and hope you can tell me the right way. Thanks.
![](http://i.imgur.com/NvYbL1J.png)
![](http://i.imgur.com/eVhWNld.png)

**Comment by daleroberts** [comment]
What does the command 'ipy' do compared to running 'ipython'? Is it a
short-cut to specify some configuration settings? Perhaps you are
overriding the backend selection?

**Comment by peinan** [comment]
No, 'ipy' is the same as 'ipython'.

**Comment by daleroberts** [comment]
Could you run the command `import matplotlib;
print(matplotlib.get_backend())` and tell me the response?

**Comment by peinan** [comment]
Okay.
```python
In [1]: import matplotlib

In [2]: print(matplotlib.get_backend())
module://ipykernel.pylab.backend_inline

In [3]:
```

**Comment by daleroberts** [comment]
It has something to do with your config. It should say:
```python
In [1]: import matplotlib; matplotlib.get_backend()
Out[1]: 'module://itermplot'
```

**Comment by peinan** [comment]
Oh...the python shell's matplotlib backend is the correct one.
```python
>>> import matplotlib
>>> print(matplotlib.get_backend())
module://itermplot
>>>
```
Thank you for the help. I'll review my ipython settings.
Please close this issue.

**Comment by daleroberts** [comment]
Thanks.

**Comment by littlehome-eugene** [comment]
I'm running inside ein (https://github.com/millejoh/emacs-ipython-notebook)
and getting the same problem


```
In [17]:
import matplotlib; print(matplotlib.get_backend())
module://itermplot


In [16]:
import matplotlib.pyplot as plt
import numpy as np

plt.imshow(np.random.random_integers(0, 255, (100,100,3)))
plt.show()
/Users/eugenekim/virtualenvs/study/lib/python3.7/site-packages/ipykernel_launcher.py:4: DeprecationWarning: This function is deprecated. Please call randi\
nt(0, 255 + 1) instead
  after removing the cwd from sys.path.

```
