### ISSUE TITLE
Wrong colors (not inverted for dark terminal)

### ISSUE THREAD

**Issue by gordio** [daleroberts/itermplot#26]
I miss option, or it's bug?
<img width="255" alt="screen shot 2017-08-10 at 15 36 28" src="https://user-images.githubusercontent.com/141126/29170532-bc22cc16-7de1-11e7-929e-548f25251748.png">

macOS v.: 10.12.6 (16G29)
iTerm v.: Build 3.1.beta.6
itermplot==0.20
matplotlib==2.0.2

**Comment by caesar** [comment]
You need to enable inverted colours with `export ITERMPLOT=rv`, did you do that?

**Comment by gordio** [comment]
No. I read "Reverse video" and think "Ok, I don't use video… Skip…" :-)
