### ISSUE TITLE
Make Python package

### ISSUE THREAD

**Issue by stsievert** [daleroberts/itermplot#3]
In the readme you say "have itermplot.py somewhere on your PTHONPATH." This can be accomplished by running "Python setup.py install" or "pip install <name>". All this really requires is the creation of a setup.py file.

**Comment by daleroberts** [comment]
Agree, I'll get around to it soon.

**Comment by daleroberts** [comment]
@stsievert Does that `setup.py` look good to you?

**Comment by stsievert** [comment]
Looks good to me. I’d upload to PyPI as well.
