### ISSUE TITLE
0.321 install fails for Python 2.7

### ISSUE THREAD

**Issue by bjarchi** [daleroberts/itermplot#31]
I had a previous version of itermplot (0.20) installed under my py2 environment, which worked fine. Upgrading to or installing 0.321, however, fails under Python2 (2.7.14, Mac OS 10.12.6). Installing 0.321 under my Python3 environment works fine. 

If Python2 support is deprecated then feel free to close this issue, but Readme.md still states (grudging) support for py2 :)

Here's the error. I don't have time to troubleshoot right now but I might be able to in the future. 

```
Collecting itermplot
  Using cached https://files.pythonhosted.org/packages/13/a6/10f9d43993d383aa289adb5b19f1e1448703fa8eec5edb75e1ebc34de909/itermplot-0.321.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/jq/sfgkbsys7kd6x00ds61hb2h46z5sy9/T/pip-install-eSstAT/itermplot/setup.py", line 7, in <module>
        with open(path.join(here, 'README'), encoding='utf-8') as f:
    TypeError: 'encoding' is an invalid keyword argument for this function

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/jq/sfgkbsys7kd6x00ds61hb2h46z5sy9/T/pip-install-eSstAT/itermplot/
```

**Comment by daleroberts** [comment]
Try now? I haven't tested it on Python 2 but hopefully *fingers crossed* it works.

**Comment by bjarchi** [comment]
Sorry for the delayed reply. 0.322 successfully installs on Python2 (2.7.15) so I think this issue can be closed.
