### ISSUE TITLE
TMUX vim slime

### ISSUE THREAD

**Issue by brijow** [daleroberts/itermplot#47]
When I select a set of lines in vim and send to other tmux pane using vim slime, the plot gets drawn in the same pane as my editor:

before sending lines:
<img width="1680" alt="Screen Shot 2021-07-09 at 8 49 16 AM" src="https://user-images.githubusercontent.com/11220949/125104803-a13e6500-e092-11eb-8ac2-20fd18a46c1c.png">

after sending lines:
<img width="1680" alt="Screen Shot 2021-07-09 at 8 49 28 AM" src="https://user-images.githubusercontent.com/11220949/125104841-abf8fa00-e092-11eb-9676-3904764ad575.png">

**Comment by daleroberts** [comment]
Unfortunately, I believe this has to do with the way that vim slime works and nothing that my library has any control over. My guess is that iterm draws the image where the cursor location is and I'm guessing when commands are sent to the right window by tmux slime, it instantly places the cursor back in the left window?

**Comment by kiedanski** [comment]
Hi, did you manage to solve this issue?
