### ISSUE TITLE
is there any way to change figsize in terminal?

### ISSUE THREAD

**Issue by gathierry** [daleroberts/itermplot#53]
If I'm not able to change the python code and set `rcParams` in python.
Is there any way to change the figure size in terminal? like set environment variables?

**Comment by daleroberts** [comment]
You can set the height in terms of the number of lines using the `ITERMPLOT_LINES` environment variable. Unfortunately, setting width has not been implemented but I accept pull requests if you want to have a go.

**Comment by gathierry** [comment]
I realized that changing number of lines is what I need as the width is zoomed as well
