### ISSUE TITLE
Installation doesn't work for me

### ISSUE THREAD

**Issue by themightyoarfish** [daleroberts/itermplot#6]
I don't know how to diagnose this really, but I have ran `sudo pip install itermplot` which installs to `/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages` on my system. My package path contains this directory 
```
In [5]: sys.path
Out[5]:
['',
 '/opt/local/Library/Frameworks/Python.framework/Versions/3.5/bin',
 '/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python35.zip',
 '/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5',
 '/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/plat-darwin',
 '/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/readline',
 '/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/lib-dynload',
 '/Users/Rasmus/Library/Python/3.5/lib/python/site-packages',
 '/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages', # <=====
 '/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/IPython/extensions',
 '/Users/Rasmus/.ipython']
```
I have also `export`ed the `MLPBACKEND` var:
```
echo $MPLBACKEND
module://itermplot
```

Still, when trying to run a script with plotting, I get an import error stating that the `itermplot` module was not found. How can I diagnose this?

**Comment by josephtbenton** [comment]
I'm having the same issue

**Comment by themightyoarfish** [comment]
Nice. Can someone tell me how to access config parameters relating to this backend in my `ipython_kernel_config.py`? For the matplolib inline backend I would use 
```
c = get_config()
c.InlineBackend.rc = {'figure.figsize': (10,10) }
```
but what do I do to increase the size of my figures in iTerm?
