### ISSUE TITLE
Uninstall renders matplotlib unusable

### ISSUE THREAD

**Issue by themightyoarfish** [daleroberts/itermplot#7]
In order for matploblib to be usable again after uninstall, one must set the backend again. After `pip uninstall itermplot` and removing `$MPLBACKEND`, iPython still tries to use this backend. Tunning `%pylab` once in the console fixes the problem. This should be at least documented.

**Comment by daleroberts** [comment]
I've improved the documentation. Thanks for the comment @themightyoarfish
